default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

joint_limits:
  revolute_1:
    has_position_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_acceleration: 0.0

    revolute_2:
    has_position_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_acceleration: 0.0
    
    revolute_3:
    has_position_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_acceleration: 0.0

    revolute_4:
    has_position_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_acceleration: 0.0

    revolute_5:
    has_position_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_acceleration: 0.0